service: summary-notice-tweet

provider:
  name: aws
  ecr:
    scanOnPush: true
    images:
      pokemon-friendly-competition-summary-notifier:
        path: ./docker/

  region: ap-northeast-1
  memorySize: 512
  logRetentionInDays: 30
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource:
        - "*"
    - Effect: "Allow"
      Action:
        - "kms:Decrypt"
      Resource:
        - "*"
    - Effect: "Allow"
      Action:
        - "ssm:GetParameter"
        - "ssm:GetParameters"
        - "ssm:GetParametersByPath"
      Resource:
        - "arn:aws:ssm:${aws:region}:${aws:accountId}:parameter/competition-notifier/twitter/*"
        - "arn:aws:ssm:${aws:region}:${aws:accountId}:parameter/competition-notifier/google/*"

  environment:
    TodayCompetitionSummaryTweetFunctionName: today-competition-summary-tweet
    ComingCompetitionTweetFunctionName: coming-competition-summary-tweet

plugins:
  - serverless-prune-plugin
  
custom:
  prune:
    automatic: true
    number: 10

functions:
  TodayCompetitionSummaryTweet:
    name: ${self:provider.environment.TodayCompetitionSummaryTweetFunctionName}
    image:
      name: pokemon-friendly-competition-summary-notifier
      command:
        - src/today_tweet.lambda_handler
    description: A function to tweet today's list of friendly competition with accompanying images.
    environment:
      SPREAD_SHEET_KEY_SSM_PARAM_NAME: /competition-notifier/google/spread-sheet-key
      GCP_KEY_SSM_PARAM_NAME: /competition-notifier/google/gcp-key
      TWITTER_CONSUMER_KEY_SSM_PARAM_NAME: /competition-notifier/twitter/consumer-key
      TWITTER_CONSUMER_SECRET_SSM_PARAM_NAME: /competition-notifier/twitter/consumer-secrets
      TWITTER_ACCESS_TOKEN_SSM_PARAM_NAME: /competition-notifier/twitter/access-token
      TWITTER_ACCESS_TOKEN_SECRET_SSM_PARAM_NAME: /competition-notifier/twitter/consumer-access-token-secrets
      IS_TWEET: ${file(./conf/config.yml):IS_TODAY_COMPETITION_SUMMARY_TWEET}
      IMAGE_HEIGHT: 2400
      IMAGE_WIDTH: 1800
      LIST_COUNT: 72
    timeout: 300
    events:
      - schedule:
          rate: ${file(./conf/config.yml):TODAY_COMPETITION_SUMMARY_TWEET_SCHEDULE}
          enabled: ${file(./conf/config.yml):ENABLE_TODAY_COMPETITION_SUMMARY_TWEET_SCHEDULE}
          input:
            type: today
  ComingCompetitionSummaryTweet:
    name: ${self:provider.environment.ComingCompetitionTweetFunctionName}
    image:
      name: pokemon-friendly-competition-summary-notifier
    description: A function to tweet the upcoming list of friendly competition with accompanying images.
    environment:
      SPREAD_SHEET_KEY_SSM_PARAM_NAME: /competition-notifier/google/spread-sheet-key
      GCP_KEY_SSM_PARAM_NAME: /competition-notifier/google/gcp-key
      TWITTER_CONSUMER_KEY_SSM_PARAM_NAME: /competition-notifier/twitter/consumer-key
      TWITTER_CONSUMER_SECRET_SSM_PARAM_NAME: /competition-notifier/twitter/consumer-secrets
      TWITTER_ACCESS_TOKEN_SSM_PARAM_NAME: /competition-notifier/twitter/access-token
      TWITTER_ACCESS_TOKEN_SECRET_SSM_PARAM_NAME: /competition-notifier/twitter/consumer-access-token-secrets
      IS_TWEET: ${file(./conf/config.yml):IS_COMING_COMPETITION_SUMMARY_TWEET}
      IMAGE_HEIGHT: 2400
      IMAGE_WIDTH: 1800
      LIST_COUNT: 72
    timeout: 300
    events:
      - schedule:
          rate: ${file(./conf/config.yml):COMING_COMPETITION_SUMMARY_TWEET_SCHEDULE}
          enabled: ${file(./conf/config.yml):ENABLE_COMING_COMPETITION_SUMMARY_TWEET_SCHEDULE}
          input:
            type: today