# 本日開催大会ツイート設定
TODAY_COMPETITION_SUMMARY_TWEET_SCHEDULE: "cron(0 3 * * ? *)"
ENABLE_TODAY_COMPETITION_SUMMARY_TWEET_SCHEDULE: true
IS_TODAY_COMPETITION_SUMMARY_TWEET: on

# 近日中開催大会ツイート設定
COMING_COMPETITION_SUMMARY_TWEET_SCHEDULE: "cron(0 10 ? * MON,THU *)"
ENABLE_COMING_COMPETITION_SUMMARY_TWEET_SCHEDULE: true
IS_COMING_COMPETITION_SUMMARY_TWEET: on
