service: general-notice-tweet

provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-1
  memorySize: 256
  logRetentionInDays: 30
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "kms:Decrypt"
      Resource:
        - "*"
    - Effect: "Allow"
      Action:
        - "ssm:GetParameter"
        - "ssm:GetParameters"
        - "ssm:GetParametersByPath"
      Resource:
        - "arn:aws:ssm:${aws:region}:${aws:accountId}:parameter/competition-notifier/twitter/*"

  environment:
    GeneralNoticeTweetFunctionName: general-notice-tweet

packages:
  exclude:
    - node_modules/**

plugins:
  - serverless-prune-plugin
  
custom:
  prune:
    automatic: true
    number: 10

functions:
  generalNoticeTweet:
    name: ${self:provider.environment.GeneralNoticeTweetFunctionName}
    handler: src/general_notice_tweet.lambda_handler
    environment:
      TWITTER_CONSUMER_KEY: ${ssm:/competition-notifier/twitter/consumer-key}
      TWITTER_CONSUMER_SECRET: ${ssm:/competition-notifier/twitter/consumer-secrets}
      TWITTER_ACCESS_TOKEN: ${ssm:/competition-notifier/twitter/access-token}
      TWITTER_ACCESS_TOKEN_SECRET: ${ssm:/competition-notifier/twitter/consumer-access-token-secrets}
      IS_TWEET: ${file(./conf/config.yml):IS_TWEET}
    timeout: 300
    events:
      - schedule:
          rate: ${file(./conf/config.yml):GENERAL_NOTICE_TWEET_SCHEDULE}
          enabled: ${file(./conf/config.yml):ENABLE_GENERAL_NOTICE_TWEET_SCHEDULE}
# ツイートの種類を増やしたい場合はfunctionを追加
#  generalNoticeTweet2:
#    name: ${self:provider.environment.GeneralNoticeTweetFunctionName2}
#    handler: src/general_notice_tweet2.lambda_handler
#    environment:
#      TWITTER_CONSUMER_KEY: ${ssm:/competition-notifier/twitter/consumer-key}
#      TWITTER_CONSUMER_SECRET: ${ssm:/competition-notifier/twitter/consumer-secrets}
#      TWITTER_ACCESS_TOKEN: ${ssm:/competition-notifier/twitter/access-token}
#      TWITTER_ACCESS_TOKEN_SECRET: ${ssm:/competition-notifier/twitter/consumer-access-token-secrets}
#      IS_TWEET: on
#    timeout: 300
#    events:
#      - schedule:
#          rate: ${file(./conf/config.yml):GENERAL_NOTICE_TWEET_SCHEDULE2}
#          enabled: ${file(./conf/config.yml):GENERAL_WEEK_NOTICE_TWEET_SCHEDULE2}