service: competition-notice-tweet

provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-1
  memorySize: 256
  logRetentionInDays: 30
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource:
        - "*"
    - Effect: "Allow"
      Action:
        - "kms:Decrypt"
      Resource:
        - "*"
    - Effect: "Allow"
      Action:
        - "ssm:GetParameter"
        - "ssm:GetParameters"
        - "ssm:GetParametersByPath"
      Resource:
        - "arn:aws:ssm:${aws:region}:${aws:accountId}:parameter/competition-notifier/twitter/*"

  environment:
    CompetitionNoticeTweetFunctionName: competition-notice-tweet

packages:
  exclude:
    - node_modules/**

plugins:
  - serverless-prune-plugin
  
custom:
  prune:
    automatic: true
    number: 10

functions:
  competitionNoticeTweet:
    name: ${self:provider.environment.CompetitionNoticeTweetFunctionName}
    handler: src/competition_notice_tweet.lambda_handler
    description: A function to tweet about each individual friendly competition.
    environment:
      SPREAD_SHEET_KEY_SSM_PARAM_NAME: /competition-notifier/google/spread-sheet-key
      GCP_KEY_SSM_PARAM_NAME: /competition-notifier/google/gcp-key
      TWITTER_CONSUMER_KEY_SSM_PARAM_NAME: /competition-notifier/twitter/consumer-key
      TWITTER_CONSUMER_SECRET_SSM_PARAM_NAME: /competition-notifier/twitter/consumer-secrets
      TWITTER_ACCESS_TOKEN_SSM_PARAM_NAME: /competition-notifier/twitter/access-token
      TWITTER_ACCESS_TOKEN_SECRET_SSM_PARAM_NAME: /competition-notifier/twitter/consumer-access-token-secrets
      IS_TWEET: ${file(./conf/config.yml):IS_TWEET}
    timeout: 300
    events:
      - schedule:
          rate: ${file(./conf/config.yml):COMPETITION_NOTICE_TWEET_SCHEDULE}
          enabled: ${file(./conf/config.yml):ENABLE_COMPETITION_NOTICE_TWEET_SCHEDULE}
          input:
            type: tweet
      - schedule:
          rate: ${file(./conf/config.yml):COMPETITION_NOTICE_RETWEET_SCHEDULE}
          enabled: ${file(./conf/config.yml):ENABLE_COMPETITION_NOTICE_RETWEET_SCHEDULE}
          input:
            type: retweet