# お知らせツイート設定
COMPETITION_NOTICE_TWEET_SCHEDULE: "cron(15 23,1-13/2 * * ? *)"
ENABLE_COMPETITION_NOTICE_TWEET_SCHEDULE: true

# 大会ツイートのリツイート設定
COMPETITION_NOTICE_RETWEET_SCHEDULE: "cron(30 23,0-13 * * ? *)"
ENABLE_COMPETITION_NOTICE_RETWEET_SCHEDULE: true

# ツイートするかどうかのフラグ。する場合はon。しない場合はon以外
IS_TWEET: on