name: Deploy weekly notice tweet

on:
  workflow_dispatch:

jobs:
  deploy-sls:
    runs-on: ubuntu-latest
    name: Deploy sls
    strategy:
      matrix:
        node-version: [18.x]
        python-version: [3.8]
        sls-prune-plugin-version: [1.4.3]
    defaults:
      run:
        working-directory: general-notifier
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "ap-northeast-1"

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: install requirement library
      run: |
        pip install --target ./ -r ./requirements.txt

    - name: Install Plugin and Deploy
      uses: serverless/github-action@v3.2
      with:
        args: -c "cd ./general-notifier && serverless plugin install --name serverless-prune-plugin@${{ matrix.sls-prune-plugin-version }} && serverless deploy"
        entrypoint: /bin/sh