name: Deploy CloudFormation

on:
  workflow_dispatch:

jobs:
  deploy-cfn:
    runs-on: ubuntu-latest
    name: Deploy CloudFormation
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-northeast-1"

      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: auto-pokemon-friendly-competition-notifier-common-infra
          template: ./common-resources/aws/cloudformation/infra.yml
