name: Remove competition notice tweet

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'remove ok?'
        required: true
        type: choice
        options:
          - "no"
          - "yes"

jobs:
  remove-sls:
    runs-on: ubuntu-latest
    name: Remove sls
    strategy:
      matrix:
        node-version: [18.x]
        sls-prune-plugin-version: [1.4.3]
    defaults:
      run:
        working-directory: competition-notifier
    if: ${{ inputs.confirm == 'yes' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Plugin and Remove
      uses: serverless/github-action@v3.2
      with:
        args: -c "cd ./competition-notifier && serverless plugin install --name serverless-prune-plugin@${{ matrix.sls-prune-plugin-version }} && serverless remove"
        entrypoint: /bin/sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}